import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { categories, categorizationRules, subcategories } from "@/db/schema";
import { requireSession } from "@/lib/session";
import { regexProblem } from "@/lib/validation";

const schema = z.object({ name: z.string().trim().min(2).max(80).optional(), field: z.enum(["merchant", "description"]).optional(), operator: z.enum(["contains", "equals", "starts_with", "regex"]).optional(), pattern: z.string().trim().min(1).max(200).optional(), categoryId: z.string().uuid().optional(), subcategoryId: z.string().uuid().nullable().optional(), priority: z.number().int().min(1).max(1000).optional(), enabled: z.boolean().optional() });

export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { try { const session = await requireSession(request); const payload = schema.safeParse(await request.json()); if (!payload.success) return Response.json({ error: "Regla no válida." }, { status: 400 }); const { id } = await context.params; const db = getDb(); const [current] = await db.select().from(categorizationRules).where(and(eq(categorizationRules.id, id), eq(categorizationRules.userId, session.userId))).limit(1); if (!current) return Response.json({ error: "Regla no encontrada." }, { status: 404 }); const problem = (payload.data.operator ?? current.operator) === "regex" ? regexProblem(payload.data.pattern ?? current.pattern) : null; if (problem) return Response.json({ error: problem }, { status: 400 }); const categoryId = payload.data.categoryId || current.categoryId; const [category] = await db.select({ id: categories.id }).from(categories).where(and(eq(categories.id, categoryId), eq(categories.userId, session.userId))).limit(1); if (!category) return Response.json({ error: "Categoría no encontrada." }, { status: 404 }); const subcategoryId = payload.data.subcategoryId === undefined ? current.subcategoryId : payload.data.subcategoryId; if (subcategoryId) { const [subcategory] = await db.select({ id: subcategories.id }).from(subcategories).where(and(eq(subcategories.id, subcategoryId), eq(subcategories.userId, session.userId), eq(subcategories.categoryId, categoryId))).limit(1); if (!subcategory) return Response.json({ error: "Subcategoría no válida para esta categoría." }, { status: 400 }); } const [rule] = await db.update(categorizationRules).set({ ...payload.data, updatedAt: Math.floor(Date.now() / 1000) }).where(and(eq(categorizationRules.id, id), eq(categorizationRules.userId, session.userId))).returning(); return Response.json({ rule }); } catch (error) { if (error instanceof Response) return error; return Response.json({ error: "No se pudo actualizar la regla." }, { status: 500 }); } }
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { try { const session = await requireSession(request); const { id } = await context.params; const [rule] = await getDb().delete(categorizationRules).where(and(eq(categorizationRules.id, id), eq(categorizationRules.userId, session.userId))).returning({ id: categorizationRules.id }); return rule ? new Response(null, { status: 204 }) : Response.json({ error: "Regla no encontrada." }, { status: 404 }); } catch (error) { if (error instanceof Response) return error; return Response.json({ error: "No se pudo eliminar la regla." }, { status: 500 }); } }
