import { ArrowRight, Check, LockKeyhole, MailCheck, ScanSearch, ShieldCheck, Sparkles, WalletCards } from "lucide-react";

const GoogleMark = () => <svg aria-hidden="true" viewBox="0 0 24 24" className="size-4"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.5-.2-2.2H12v4.3h5.4a4.7 4.7 0 0 1-2 3v2.8h3.4c2-1.8 3-4.5 3-7.9Z"/><path fill="#34A853" d="M12 22c2.8 0 5.2-.9 6.9-2.5l-3.4-2.7c-.9.7-2.1 1-3.5 1a6.1 6.1 0 0 1-5.7-4.2H2.8v2.8A10.4 10.4 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.3 13.6A6.2 6.2 0 0 1 6 12c0-.6.1-1.1.3-1.6V7.6H2.8A10.1 10.1 0 0 0 1.7 12c0 1.6.4 3 1.1 4.4l3.5-2.8Z"/><path fill="#EA4335" d="M12 6.1c1.6 0 3 .5 4 1.6l3-3A10 10 0 0 0 2.8 7.6l3.5 2.8A6.1 6.1 0 0 1 12 6.1Z"/></svg>;

export default async function LandingPage({ searchParams }: { searchParams: Promise<{ auth?: string }> }) {
  const auth = (await searchParams).auth;
  return <main className="min-h-screen overflow-hidden bg-[#f4f7f6] text-[#10231e]">
    <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
      <a href="#inicio" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[14px] bg-[#102820] text-[#c9ff4d]"><Sparkles className="size-5" /></span><span className="text-lg font-bold tracking-[-.04em]">Lúmina</span></a>
      <div className="hidden items-center gap-7 text-sm font-medium text-[#62736d] md:flex"><a href="#como-funciona" className="hover:text-[#102820]">Cómo funciona</a><a href="#privacidad" className="hover:text-[#102820]">Privacidad</a><a href="#seguridad" className="hover:text-[#102820]">Seguridad</a></div>
      <a href="/api/auth/google/start" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#102820] px-4 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-[#1b4438]"><GoogleMark /> Ingresar</a>
    </nav>
    {auth && <div role="alert" className="mx-auto mt-2 max-w-7xl px-5 sm:px-8"><div className="rounded-2xl border border-[#eccfc9] bg-[#fff3f0] px-4 py-3 text-sm text-[#823f35]">{auth === "setup" ? "El acceso con Google está pendiente de configurar por el administrador." : auth === "denied" ? "Cancelaste el acceso con Google. Lúmina necesita el permiso de solo lectura de Gmail para importar tus movimientos." : "No pudimos completar el acceso con Google. Inténtalo nuevamente."}</div></div>}

    <section id="inicio" className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-24 pt-14 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:pb-32 lg:pt-24">
      <div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#cad8d3] bg-white px-3 py-1.5 text-xs font-semibold text-[#386151]"><span className="size-1.5 rounded-full bg-[#20bb8c]" /> Gmail en modo solo lectura</div><h1 className="max-w-3xl text-[clamp(3rem,7vw,6.5rem)] font-semibold leading-[.91] tracking-[-.075em]">Tus gastos.<br/><span className="text-[#2a7b61]">Sin perseguirlos.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#60716b]">Lúmina encuentra las compras que tus bancos envían a Gmail, las ordena y te muestra exactamente dónde está yendo tu dinero.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/api/auth/google/start" className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-[#c9ff4d] px-6 font-bold text-[#102820] shadow-[0_12px_30px_rgba(112,160,25,.18)] transition hover:-translate-y-0.5"><GoogleMark /> Continuar con Google <ArrowRight className="size-4" /></a><a href="#como-funciona" className="inline-flex h-12 items-center justify-center rounded-2xl border border-[#ced9d5] bg-white px-6 font-semibold text-[#314942]">Ver cómo funciona</a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm text-[#71817b]"><span className="flex items-center gap-1.5"><Check className="size-4 text-[#20a979]"/>Sin acceso de escritura</span><span className="flex items-center gap-1.5"><Check className="size-4 text-[#20a979]"/>Cancela cuando quieras</span></div></div>
      <div className="relative mx-auto w-full max-w-[590px]"><div className="absolute -inset-20 -z-0 rounded-full bg-[#c9ff4d]/20 blur-3xl"/><div className="relative overflow-hidden rounded-[32px] border border-white/70 bg-[#112d25] p-5 shadow-[0_40px_90px_rgba(16,40,32,.22)] sm:p-7"><div className="mb-9 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold text-white"><span className="grid size-7 place-items-center rounded-lg bg-[#c9ff4d] text-[#102820]"><Sparkles className="size-3.5"/></span>Lúmina</div><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-white/60">Sincronización privada</span></div><div className="grid gap-3 sm:grid-cols-3"><FlowCard icon={<MailCheck/>} step="01" title="Detecta" text="Lee alertas financieras"/><FlowCard icon={<ScanSearch/>} step="02" title="Entiende" text="Extrae y clasifica"/><FlowCard icon={<WalletCards/>} step="03" title="Ordena" text="Convierte en claridad"/></div><div className="mt-5 rounded-[22px] bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.11em] text-[#8a9793]">Tu panorama</p><p className="mt-1 text-xl font-bold tracking-[-.04em]">Datos reales, sin digitación</p></div><div className="grid size-11 place-items-center rounded-2xl bg-[#e9f8f1] text-[#1f8e67]"><ShieldCheck className="size-5"/></div></div><div className="mt-5 grid grid-cols-4 items-end gap-2" aria-hidden="true">{[42,68,51,86,60,96,75,100].map((height,index)=><span key={index} className="rounded-t-md bg-[#2bd9a8] even:bg-[#c9ff4d]" style={{height:`${height*.72}px`}}/>)}</div></div></div></div>
    </section>

    <section id="como-funciona" className="bg-white py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><p className="section-label">Cero trabajo manual</p><div className="mt-3 grid gap-6 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><h2 className="text-[clamp(2.4rem,5vw,4.8rem)] font-semibold leading-[.95] tracking-[-.06em]">De correo a decisión, automáticamente.</h2><p className="max-w-xl text-lg leading-8 text-[#66766f] lg:justify-self-end">Conectas una vez. Lúmina identifica el banco, comercio, monto, moneda y tarjeta; evita duplicados y aprende de tus correcciones.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Feature number="01" title="Conecta Gmail" text="Google OAuth y un único permiso: leer correos. Nunca enviamos, borramos ni modificamos mensajes."/><Feature number="02" title="Sincroniza" text="Los parsers bancarios procesan solo alertas relevantes y recuerdan el último punto sincronizado."/><Feature number="03" title="Toma el control" text="Filtra, corrige categorías, crea reglas y registra movimientos manuales desde cualquier dispositivo."/></div></div></section>

    <section id="privacidad" className="bg-[#102820] py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:items-center"><div><span className="grid size-12 place-items-center rounded-2xl bg-[#c9ff4d] text-[#102820]"><LockKeyhole className="size-6"/></span><h2 className="mt-7 text-[clamp(2.4rem,5vw,4.6rem)] font-semibold leading-[.96] tracking-[-.06em]">Tu bandeja sigue siendo tuya.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/58">Guardamos únicamente los datos financieros normalizados que necesitas. Los tokens se cifran y cada cuenta queda estrictamente aislada.</p></div><div id="seguridad" className="grid gap-3 sm:grid-cols-2"><PrivacyItem title="Solo lectura" text="Scope exclusivo gmail.readonly."/><PrivacyItem title="Tokens cifrados" text="AES-GCM antes de persistir."/><PrivacyItem title="Tarjetas seguras" text="Solo marca y últimos 4 dígitos."/><PrivacyItem title="Control total" text="Edita o elimina tus datos."/></div></div></section>
    <section className="px-5 py-20 sm:px-8"><div className="mx-auto flex max-w-5xl flex-col items-center rounded-[32px] bg-[#c9ff4d] px-6 py-14 text-center sm:px-12"><h2 className="text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Tu claridad financiera empieza en Gmail.</h2><p className="mt-4 max-w-xl text-[#315039]">Conecta tu cuenta y deja que Lúmina organice lo que ya está en tu bandeja.</p><a href="/api/auth/google/start" className="mt-7 inline-flex h-12 items-center gap-2 rounded-2xl bg-[#102820] px-6 font-bold text-white"><GoogleMark/> Continuar con Google</a></div></section>
    <footer className="border-t border-[#dce4e1] px-5 py-8 text-sm text-[#74827d] sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Lúmina</span><div className="flex flex-wrap gap-5"><a href="/privacy" className="font-semibold text-[#4d655d] hover:text-[#102820]">Política de privacidad</a><a href="https://github.com/SrEnderGYT/lumina-finanzas" className="hover:text-[#102820]">Código fuente</a></div></div></footer>
  </main>;
}

function FlowCard({ icon, step, title, text }: { icon: React.ReactNode; step: string; title: string; text: string }) { return <div className="rounded-[20px] border border-white/10 bg-white/[.065] p-4 text-white"><div className="flex items-center justify-between"><span className="[&_svg]:size-5 text-[#c9ff4d]">{icon}</span><span className="text-[11px] text-white/35">{step}</span></div><p className="mt-7 font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-white/48">{text}</p></div>; }
function Feature({ number, title, text }: { number: string; title: string; text: string }) { return <article className="rounded-[24px] border border-[#dce5e2] bg-[#f7f9f8] p-6"><span className="text-xs font-bold text-[#1f9f72]">{number}</span><h3 className="mt-10 text-xl font-semibold tracking-[-.035em]">{title}</h3><p className="mt-3 leading-7 text-[#6c7b76]">{text}</p></article>; }
function PrivacyItem({ title, text }: { title: string; text: string }) { return <article className="rounded-[22px] border border-white/10 bg-white/[.06] p-5"><ShieldCheck className="size-5 text-[#c9ff4d]"/><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-white/48">{text}</p></article>; }
